### PR TITLE
Task manager API

### PR DESCRIPTION
**Pull request by adityasunny1189**
Implement a RESTful API with the following endpoints:

- [x] GET /tasks: Retrieve all tasks.
- [x] GET /tasks/:id: Retrieve a single task by its ID.
- [x] POST /tasks: Create a new task.
- [x] PUT /tasks/:id: Update an existing task by its ID.
- [x] DELETE /tasks/:id: Delete a task by its ID.

### CODE REVIEW

**Comment by sagarsakri** [comment]
Hi @adityasunny1189 
Please add me as a reviewer for the PR

**Comment by sagarsakri** [comment]
@adityasunny1189 please share the api responses from postman here

**Comment by adityasunny1189** [comment]
> @adityasunny1189 please share the api responses from postman here

ok i will add these and also add you as reveiwer

**Comment by adityasunny1189** [comment]
> @adityasunny1189 please share the api responses from postman here

https://api.postman.com/collections/10462467-cf287b10-3ca0-4051-aa53-6e5394eb7fb7?access_key=PMAT-01H720RZEHC2QW0QKW87FNK896

**Pull request merged**
